CREATE TABLE Usuario(
	Id INT AUTO_INCREMENT PRIMARY KEY,
	Nome VARCHAR(40),
	CPF VARCHAR(11),
	saldo VARCHAR(100),
	email VARCHAR(100),
	Senha VARCHAR(40),
	telefone VARCHAR(14),
	aniversario DATE
);


